apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: eks-manifest
  namespace: argocd
spec:
  destination:
    namespace: eks-manifest
    server: https://kubernetes.default.svc
  project: default
  source:
    path: backend
    repoURL: git@github.com:jbseooo/service-repository.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
    - CreateNamespace=true